// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCD9_VTn-Dt24gj5bCGPrBmHMw3SLXlYo',
    appId: '1:692311134390:web:45e20c1cdf0ca03cd85617',
    messagingSenderId: '692311134390',
    projectId: 'workoutlog-62209',
    authDomain: 'workoutlog-62209.firebaseapp.com',
    storageBucket: 'workoutlog-62209.firebasestorage.app',
    measurementId: 'G-S17HTMP7N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23y4UNlicJ8IA8tAqHF7igCWQshzJVWY',
    appId: '1:692311134390:android:bfde2f4967dc6eddd85617',
    messagingSenderId: '692311134390',
    projectId: 'workoutlog-62209',
    storageBucket: 'workoutlog-62209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVsakhguzqKUdI-zwo5w8PKH4gK7KL3g',
    appId: '1:692311134390:ios:6ea3fe13747d2db0d85617',
    messagingSenderId: '692311134390',
    projectId: 'workoutlog-62209',
    storageBucket: 'workoutlog-62209.firebasestorage.app',
    iosBundleId: 'com.example.workoutLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVsakhguzqKUdI-zwo5w8PKH4gK7KL3g',
    appId: '1:692311134390:ios:6ea3fe13747d2db0d85617',
    messagingSenderId: '692311134390',
    projectId: 'workoutlog-62209',
    storageBucket: 'workoutlog-62209.firebasestorage.app',
    iosBundleId: 'com.example.workoutLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCD9_VTn-Dt24gj5bCGPrBmHMw3SLXlYo',
    appId: '1:692311134390:web:e9f829ab49d8b437d85617',
    messagingSenderId: '692311134390',
    projectId: 'workoutlog-62209',
    authDomain: 'workoutlog-62209.firebaseapp.com',
    storageBucket: 'workoutlog-62209.firebasestorage.app',
    measurementId: 'G-RSVYBPJLKM',
  );
}
